### ISSUE TITLE
support Windows build

### ISSUE THREAD

**Issue by j042** [tataratat/bezman#10]
I'd like to add windows build for splinepy. Noticed that bezman cause errors with MSVC. You can see the logs [here](https://github.com/tataratat/bezman/actions/runs/4121966355/jobs/7118189763). Can we fix this @jzwar @deltaLuki ?

**Comment by deltaLuki** [comment]
I think the problem is the msvc version (outdated). We need for [c++17](https://en.cppreference.com/w/cpp/compiler_support/17), MSVC with version 19.++. I only find this [versions](https://github.com/actions/runner-images/blob/releases/win22/20230307/images/win/Windows2022-Readme.md). But it seems to me that the versions don't match because I don't think that the runners only support such old versions. Maybe someone else has an explanation.
